name: Build 3DX .NET Core SDK Solution and Push NUGET Packages

on:
  pull_request:
    branches: [ master ]

env:
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}\output
# NUGET_SOURCE_URL: '"https://api.nuget.org/v3/index.json"'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
#    - id: file_changes
#      uses: jitterbit/get-changed-files@v1
#    - name: List all modified files
#      run: echo ${{ steps.file_changes.outputs.modified}}
